	
	window.gameUrlDic = {
		"default": ["3m8x0Gkutqw"
					, "FAaNXqV6lBI"
					, "0r0qOvOHYSY"
					, "MWqcq8v_jN8"
					, "u4zMQ6L5jQM"
					, "aklA2JkDWNc"
					, "ecBRI_8oHsA"
					],
		"forcez-io": ["8jw5aeXxg4o"],
		"stunt-simulator": ["-IoPQgBq6wA"],
		"masked-forces-crazy-mode": ["h9lG9_xGl2U"],
		"cars-simulator": ["QMHCKWClqdQ"],
		"city-driver": ["zh1GtDf3STA"],
		"dragon-simulator-multiplayer": ["ffM5khn5ZN4"],
		"dragon-slayer-fps": ["xO_oBuhbI4g"],
		"drift-cars": ["2iKDnMTje6Q"],
		"mob-city": ["4JpFOmQbVLk"],
		"motorbike-simulator": ["CDIWIVlAHwA"],
		"puppet-killer": ["kLbqbwARxBw"],
		"shooterz-io": ["o42Srt-_DZk"],
		"sniper-strike": ["FDQU4jc_tEk"],
		"snow-war-io": ["oE7SJbqyJMQ"],
		"stunt-crasher": ["5C3RfJe_2v4"],
		"toy-cars": ["N_fL5d73boM"],
		"vehicles-simulator": ["rLjn5HP5tEg"],
		"highway-traffic": ["o0-oPSIVITY"
							, "ncBFixLd6Sc"],
		"stackballio": ["bmd0SBKTHEo"],
		"void-city": ["W2fYxUG4Yos"],
		"pixelforces-io": ["0rzgTBetHos"],
		"city-car-simulator": ["zHwNFxdGbc8"],
		"zombie-derby": ["Sq_Nve_iDhg"],
		"masked-forces": ["05T-fbQ7nbE"],
		"pixel-battle-royale": ["CKOgJZd0WvY"],
		"pixel-survival": ["vrxZJTOcNBM"],
		"unblocked-shooters": ["q6J39_RT-yg"],
		"slither-snakes": ["aX7SfH9I7bg"],
		"archer-ro": ["AU1-vb-H_ic"],
		"hook": ["ma3VtgMMnK0"],
		"crazy-shooters-2": ["HfzAO2OG49Q"],
		"spaceguard-io": ["xcC-Fd75p8I"],
		"sportbike-simulator": ["F1q9uynKUA0"],
		"bicycle-simulator": ["Nz7gaMzaoJ4"],
		"masked-forces-3": ["qO-aUYuVrik"],
		"tank-war-simulator": ["marY5Sj8pLo"],
		"stickman-ragdoll": ["tYgf1dlxzQM"],
		"fort-shooter-simulator": ["wjFoUwUHNmU"],
		"realistic-buggy-driver": ["aLxXDgJNe5Y"],
		"pipe-ninja": ["qFCgfqMhAHg"],
		"assault-fury": ["7XNnEML_QEU"],
		"horse-riding-simulator": ["FUIDFYqUgxw"],
		"stunt-simulator-multiplayer": ["cywc8my4hlU"],
		"thief-ro": ["Cagaoze5FBA"],
		"boat-simulator": ["BIxZnIJGrw8"],
		"monoa-city-parking": ["WJS0eGz9Bj4"],
		"vehicles-simulator-2": ["Zg55bkSJX9Y"],
		"cobraz-io": ["h5eEe0X6L5M", "SSC-SL1d7I0"],
		"kingdom-attack": ["YAovF2Onk7c"],
		"stickman-destruction": ["D66rmZ5Zjsw", "m1tPzrLil3s"],
		"car-transform-racing": ["z9dpsz7ubPM", "sSh9o2BSs9s"],
		"zodiac-runner": ["0CtOg6ePp_E", "1uqHYBpSYM0"],
		"fidget-spinner-master": ["zjDvx0oxJNU", "gL76CgrtG8Q"],
		"marble-zumba-stack": ["7vKCOPERDNg", "L6n9H20J5TU"],
		"bus-subway-runner": ["uOtONXnTvsI", "w4HA1bEp-mw"],
		"fall-heroes-knockout": ["pSrRSpSLrEU", "C4Uy8JPND94", "iKg0rtCHAB0"],
		"armedforces-io": ["Ts58-TdSSMs", "_wJMBKPhByM"],
		"dragons-ro": ["QClV4Hvc934"],
		"dragon-world": ["m_N_-i8YXNM"],
		"dragon-city": ["jQWk30uwGUE"],
		"kick-the-teddy-bear": ["XAGOdDscTIw"],
		"police-chase-drifter": ["w2jL8Z6ArMQ"],
		"draw-the-bridge": ["lc09cl9c8zM"],
		"draw-the-car-path": ["nH99y7vlMqE"],

		"mine-clone": ["dqFYEU7U_m8"],
		"exploration-craft": ["hyb2wBXlli4"],
		"airplane-racer": ["jUMxtM5_IZo"],
		"kick-the-dummy": ["pgsqcFfdmwo"],
		"underworld-survival": ["dO9m2iTnp6E"],
		"fantasy-tower-defense": ["7TZqQ50XBM8"],
		"jul-monster-truck-racing": ["dy65EBHV4sM", "EvyMmzisbsU"],
		"tank-racing": ["er5PJkQsFJ4"],
		"speedrun-parkour": ["XgJRkO0QFwM", "ScVw-5lWyq8"],
		"formula-1-driver": ["bqBYPAFnAuA"],
		"draw-the-bird-path": ["L94X6We7Lvs"],
		"speed-drift-racing": ["XcFViFtT4ag"],
		"neon-moto-driver": ["FuCG5Z4ft2Q"],
		"draw-the-truck-bridge": ["VVyUhiW2HbM", "8_5kUlJOlLw"],
		"truck-racing": ["LLoHLjttTp8"],
		"kick-the-pirate": ["Pi8ZcaI3Og0"],
		"heroes-battle": ["2iNeuUuiPg8"],
		"fortress-defense": ["40M1aBk30Wg"],
		"mech-shooter": ["mMe9PP7Gfas"],
		"draw-the-bike-bridge": ["1OXIjTebviU"],
		"f1-drift-racer": ["VE73UOdku7w", "7iTcT9qDTB0"],
		"car-parkour": ["uuPsk6KWE7Y", "_Y50PzD8HJ0"],
		"army-driver": ["AafCDbeD2r8"],
		"forest-slither-snake": ["qUcQt64zHFk"],
		"secret-sniper-agent": ["T_bbDB_aeUQ"],
		"zombie-war-defense": ["rJJhlmuQp1A"],
		"the-farmer": ["IpafFefg_hw"],
		"jul-moto-racing": ["FIcVCSKVERg"],
		"train-racing": ["r5Pk1z3fZ8U"],
		"heist-escape": ["IYbFTacXTy0"],
		"galactic-driver": ["MjgyUJMijpA"],
		"galactic-traffic": ["L8Q54rnkK9I"],
		"basketball-io": ["mE1_QApQvCA"],
		"crazy-battle-royale": ["SGiAVITwpB8"],
		"mini-zombie-shooters": ["nd3zyFcPTrY"],
		"battle-royale-simulator": ["6xZtGnzMRJU"],
		"blocky-parkour-ninja": ["Q-cgbw1n8Yg", "X44jALj88Tk"],
		"masked-special-forces": ["8Ut7QdZMPM4", "3zzQSps5dbc"],
		"war-of-ships-io": ["G66Iy7NvHbY"],
		"dino-evolution-io": ["Jy3jdRn1V1M"],
		"8-ball-pool-billiard": ["qALBTA-AGQ8"],
		"waterpark-slide-io": ["S4Qu89yIVgA"],
		"skateboard-marathon": ["KzwHB07m4Hs"],
		"stick-guys-defense": ["X5pmddGognQ"],
		"poly-racing-cars": ["isdR1YUub2A"],
		
		"cobraz-io-classic": ["UaWi2n7vwbc"],
		"sweet-sugar-match": ["l1hwgBHHYs8"],
		"tractor-farming-simulator": ["_4Lfh3Io8vA"],
		"city-ambulance-driver": ["8jS7R_x6AEk"],
		"stellar-shooters": ["n5MjVqZhfUU"],
		"limousine-driver": ["OGklG1V-JpA"],
		"chicken-shooter": ["llDqq6Yd9c0"],
		"water-slide-cars": ["aAAxRyBtfmA"],
		"cargo-truck-simulator": ["hQntM4VRxUo"],
		"dino-transport-truck": ["IwgyNaHmQWU"],
		"watermelon-shooter": ["sIHMwRGe_3I"],
		"water-car-surfing": ["TE3zB_0LC50"],
		"drift-simulator": ["O5O00-4zSi4"],
		"car-carrier-trailer": ["Bq_6HQ2BYd0"],
		"taxi-simulator": ["e56tzyz6Xek"],
		"snow-hill-racing": ["boh9a7AFQ4c"],		
		"storm-city-mafia": ["ZhBCg8_E9H0"],
		"furious-car-racing": ["FqqveN_cAx4"],
		"arena-of-heroes": ["8SdiuIVEoBI"],
		"survival-craft": ["q3CWU-Tv9MU"],
		"fnf-funk-3d": ["xiREdRBpIxA"],
		"drako-io": ["oCRDgm6ebhQ"],
		"edys-car-simulator": ["VuKKOGhCfeQ"],
		
		"squid-race-simulator": ["a5bLyPf-Tpc"],
		"toonz-io": ["TB3UHOtFFnE"],
		"grandmaster-chess": ["kuX1ianK_O0"],
		
		"dragon-escape": ["n0nMQb5RsN4"],
		"hover-racer": ["UFBUDjWYLNs"],
		"alien-sky-invasion": ["KLukpPP9AAM"],
		"stunt-simulator-2": ["eQBrGj1C9UI"],
		"masked-forces-zombie-survival": ["J-9sxzwlfF8"],
		"american-touchdown": ["eS0rD2-XVkY"],
		"pixel-driver": ["ygZUBhBjRAA"],
		"legendary-sniper": ["yLlCoXqGrl4"],
		
		"bandits-multiplayer-pvp": ["73beNvkqNyQ"],
		"fighter-emily": ["4kSBkqfVw5I"],
		"blocky-blast": ["VQVCX0jJyoE"],
		"draw-here": ["H_4BrKjXq-c"],
		"sniper-reloaded": ["iVm5SDQxaXo"],
		"pinball-simulator": ["Vp3uMuWIqQE"],
		"zombie-road": ["Dud5z3VoLKI"],
		"wasteland-shooters": ["_R4eeJOlAy0"],
		"masked-shooters-assault": ["jBkr0pZS0iU"],
		"worms-combat-coop": ["PMtzmEIdB00"],
		"mini-shooters": ["XbtuD_8Y9K4", "K2u2433_h7w"],
		"arena-shooter": ["0hRftuQehxQ"],
		"war-simulator": ["RfHUs1TYFtg"],
		"nova-billiard": ["dJuVrQx0mlQ"],
		"deathmatch-combat": ["JYYRizU4oj0"],
		"crazy-ball-adventures": ["6jrdn2ge8co"],
		"basketball-slam-dunk": ["I7nXS9QQaQY"],
		"mister-bullet-gun": ["6SFUXHyOozQ"],
		"arcade-car-drift": ["bgPoCy1Gh1U"],
		"tic-tac-toe": ["i1V8-Lm7ph0"],
		"motorbike-stunt-simulator": ["R7ds-xd8DKc"],
		"soul-essence-adventure": ["Z8fiw4GGp70"],
		"moto-trials": ["FdFcI6UTsHk"],
		"neon-racer": ["qex3ER9c_RE"],
		"cargo-jeep-racing": ["U2MB5IIRXCk"],
		"car-tracks-unlimited": ["buIV02GoP1o"],
		"monster-truck-city-parking": ["UpJfC7qTniw"],
		"moto-beach": ["yFD9eDbumDM"],
		"rome-simulator": ["NpDzlTig1ic"],
		"mad-combat-marines": ["vMRk1Dmfmfc"],
		"mini-cars-racing": ["RVNXXUYWYJI"],
		"dockyard-tank-parking": ["iJ4zQUwX64U"],
		"agent-smith": ["kJc2tkxmG-E"],
		"atv-highway-traffic": ["fg7Jb0nCzzo"],
		"police-traffic": ["jAn7IbEcMmU"],
		"motorbike-traffic": ["8psqnIZUdBM"],
		"jacks-village": ["Ikcd1yn_pyQ"],
		"dont-fall-io": ["g6QSXEO8b40"],
		"stack-fire-ball": ["dJ3uQDlne2s"],
		"heavy-combat": ["eEddnXEoH7M"],
		"heavy-combat-zombies": ["UOrDqCjruIo"],
		"army-combat": ["pkzWAQra30"],
		"evo-deathmatch-shooter": ["E0lqsbjks9c"],
		"demolition-derby": ["L1ul6t_XBgQ"],
		"real-flight-simulator": ["xrbq8bQ2k4Q"],
		"highway-racer-2": ["eYgEVLLzflo"],
		"drift-fury": ["A0UVKu6T3KA"],
		"hero-rush-tower-defense": ["ejp-IZqqurY"],
		
		
		
		
	};
